### ISSUE TITLE
Census data

### ISSUE THREAD

**Issue by CourtneyPageTan** [utn100/NCEAS-OSS2017-Project2#1]

**Comment by ascyoung** [comment]
Hey, I wrote a R script to pull down census data from the R acs package last night. I will show people today in group. I think it will help with our proprietary issues.

**Comment by ascyoung** [comment]
install.packages(acs)
library(acs)
#census_api_key("4ddd49b8e2809e4638d9833ecd06d026b40a8443")
api.key.install(key="4ddd49b8e2809e4638d9833ecd06d026b40a8443")
coastal_counties <- read.csv("coastal_counties.csv")

#county_lookup <- function(datain) {
  #mygeo <- geo.make(state=datain[2],datain[3],tract="*")
  #mydata <- acs.fetch(geo=mygeo, endyear=2011, table.number="B01003")
  #return(mydata)
#}
#popdata <- apply(coastal_counties,1, county_lookup)

citrus <-geo.make(state=12, county=17, tract="*")
acs.fetch(geo=citrus, endyear=2010, table.number="B01003")

#FL_escambia <- geo.make(state="FL", county="Escambia", tract="*") 
#acs.fetch(geo=FL_escambia, endyear=2011, table.number="B01003")

#coastal.tracts=geo.make(state=fips.county[random.counties,1], 
#county=fips.county[random.counties,3], tract="*", check=T)

**Comment by CourtneyPageTan** [comment]
ACS code:
https://www.socialexplorer.com/data/ACS2010/metadata/?ds=ACS10

**Comment by CourtneyPageTan** [comment]
ACS codes for our Bonding Social Capital indicators:
https://docs.google.com/spreadsheets/d/184qrB0-CHCsT1UIc9h84U4Q7tUJ2ANA_byfqqMtihGk/edit?usp=sharing

**Comment by CourtneyPageTan** [comment]
**First draft of social and demographic dataset:**

[Social and Demographic Data.txt](https://github.com/utn100/NCEAS-OSS2017-Project2/files/1161602/Social.and.Demographic.Data.txt)

[Social and Demographic FIPS Key.txt](https://github.com/utn100/NCEAS-OSS2017-Project2/files/1161604/Social.and.Demographic.FIPS.Key.txt)

**Comment by CourtneyPageTan** [comment]
- [x] Add GINI index to dataset with @ascyoung 's code

**Comment by CourtneyPageTan** [comment]
- [x] Gender inequality data from ACS

**Comment by CourtneyPageTan** [comment]
GINI data is here: https://github.com/utn100/NCEAS-OSS2017-Project2.git
