### ISSUE TITLE
Built data

### ISSUE THREAD

**Issue by CourtneyPageTan** [utn100/NCEAS-OSS2017-Project2#2]
- [x] Download Landuse Dataset

- [x] Write function to aggregate cover classes by county

- [x] Apply function to all states and years

- [x] Upload county-level count data to aurora

**Comment by vdtobias** [comment]
I uploaded the compiled land use data to aurora today

**Comment by vdtobias** [comment]
I just uploaded the land use percent cover dataset to aurora- It's called  lulc_all_perc.csv.  The dataset called lulc_all.csv has raw pixel counts.
